spring:
  application:




liquibase:
    change-log: classpath:/db/changelog/master.yaml

kafka:
  bootstrap-servers: localhost:9092
  producer:
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      spring.json.add.type.headers: true #to add info about JSON types in headers
      acks: all  #delivery guarantee(0,1,all)
      retries: 3 #number of retries in case of error
      enable-idempotence: true #protection against duplicates

app:
  kafka:
    topics:
      user-events: user-events        # Topic for user events
      dead-letter-queue: dlq-topic    # Topic for "dead" events
    retry:
      max-attempts: 3                 # max number of retries
      backoff-delay: 1000             # initial delay (ms)
      multiplier: 2.0
      max-delay: 10000                #max delay (ms)